//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace RBEPortalServer.Schema
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(aspnet_Membership))]
    [KnownType(typeof(aspnet_Paths))]
    [KnownType(typeof(aspnet_Roles))]
    [KnownType(typeof(User))]
    public partial class aspnet_Applications
    {
        public aspnet_Applications()
        {
            this.aspnet_Membership = new HashSet<aspnet_Membership>();
            this.aspnet_Paths = new HashSet<aspnet_Paths>();
            this.aspnet_Roles = new HashSet<aspnet_Roles>();
            this.aspnet_Users = new HashSet<User>();
        }
    
        [DataMember]
        public string ApplicationName { get; set; }
        [DataMember]
        public string LoweredApplicationName { get; set; }
        [DataMember]
        public System.Guid ApplicationId { get; set; }
        [DataMember]
        public string Description { get; set; }
    
        [DataMember]
        public virtual ICollection<aspnet_Membership> aspnet_Membership { get; set; }
        [DataMember]
        public virtual ICollection<aspnet_Paths> aspnet_Paths { get; set; }
        [DataMember]
        public virtual ICollection<aspnet_Roles> aspnet_Roles { get; set; }
        [DataMember]
        public virtual ICollection<User> aspnet_Users { get; set; }
    }
    
}
