//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace RBEPortalServer.Schema
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(aspnet_Applications))]
    [KnownType(typeof(User))]
    public partial class aspnet_Membership
    {
        [DataMember]
        public System.Guid ApplicationId { get; set; }
        [DataMember]
        public System.Guid UserId { get; set; }
        [DataMember]
        public string Password { get; set; }
        [DataMember]
        public int PasswordFormat { get; set; }
        [DataMember]
        public string PasswordSalt { get; set; }
        [DataMember]
        public string MobilePIN { get; set; }
        [DataMember]
        public string Email { get; set; }
        [DataMember]
        public string LoweredEmail { get; set; }
        [DataMember]
        public string PasswordQuestion { get; set; }
        [DataMember]
        public string PasswordAnswer { get; set; }
        [DataMember]
        public bool IsApproved { get; set; }
        [DataMember]
        public bool IsLockedOut { get; set; }
        [DataMember]
        public System.DateTime CreateDate { get; set; }
        [DataMember]
        public System.DateTime LastLoginDate { get; set; }
        [DataMember]
        public System.DateTime LastPasswordChangedDate { get; set; }
        [DataMember]
        public System.DateTime LastLockoutDate { get; set; }
        [DataMember]
        public int FailedPasswordAttemptCount { get; set; }
        [DataMember]
        public System.DateTime FailedPasswordAttemptWindowStart { get; set; }
        [DataMember]
        public int FailedPasswordAnswerAttemptCount { get; set; }
        [DataMember]
        public System.DateTime FailedPasswordAnswerAttemptWindowStart { get; set; }
        [DataMember]
        public string Comment { get; set; }
    
        [DataMember]
        public virtual aspnet_Applications aspnet_Applications { get; set; }
        [DataMember]
        public virtual User aspnet_Users { get; set; }
    }
    
}
