//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace RBEPortalServer.Schema
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(aspnet_Paths))]
    [KnownType(typeof(User))]
    public partial class aspnet_PersonalizationPerUser
    {
        [DataMember]
        public System.Guid Id { get; set; }
        [DataMember]
        public Nullable<System.Guid> PathId { get; set; }
        [DataMember]
        public Nullable<System.Guid> UserId { get; set; }
        [DataMember]
        public byte[] PageSettings { get; set; }
        [DataMember]
        public System.DateTime LastUpdatedDate { get; set; }
    
        [DataMember]
        public virtual aspnet_Paths aspnet_Paths { get; set; }
        [DataMember]
        public virtual User aspnet_Users { get; set; }
    }
    
}
