//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace RBEPortalServer.Schema
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(User))]
    public partial class aspnet_Profile
    {
        [DataMember]
        public System.Guid UserId { get; set; }
        [DataMember]
        public string PropertyNames { get; set; }
        [DataMember]
        public string PropertyValuesString { get; set; }
        [DataMember]
        public byte[] PropertyValuesBinary { get; set; }
        [DataMember]
        public System.DateTime LastUpdatedDate { get; set; }
    
        [DataMember]
        public virtual User aspnet_Users { get; set; }
    }
    
}
