//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace RBEPortalServer.Schema
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(aspnet_Applications))]
    [KnownType(typeof(aspnet_Membership))]
    [KnownType(typeof(aspnet_PersonalizationPerUser))]
    [KnownType(typeof(aspnet_Profile))]
    [KnownType(typeof(Log))]
    [KnownType(typeof(Resource))]
    [KnownType(typeof(aspnet_Roles))]
    [KnownType(typeof(Request))]
    [KnownType(typeof(Share))]
    public partial class User
    {
        public User()
        {
            this.PersonalizationPerUser = new HashSet<aspnet_PersonalizationPerUser>();
            this.Logs = new HashSet<Log>();
            this.ModifiedResources = new HashSet<Resource>();
            this.Roles = new HashSet<aspnet_Roles>();
            this.ModifiedRequests = new HashSet<Request>();
            this.Requests = new HashSet<Request>();
            this.ModifiedShares = new HashSet<Share>();
            this.Shares = new HashSet<Share>();
        }
    
        [DataMember]
        public System.Guid ApplicationId { get; set; }
        [DataMember]
        public System.Guid UserId { get; set; }
        [DataMember]
        public string UserName { get; set; }
        [DataMember]
        public string LoweredUserName { get; set; }
        [DataMember]
        public string MobileAlias { get; set; }
        [DataMember]
        public bool IsAnonymous { get; set; }
        [DataMember]
        public System.DateTime LastActivityDate { get; set; }
    
        [DataMember]
        public virtual aspnet_Applications Applications { get; set; }
        [DataMember]
        public virtual aspnet_Membership Membership { get; set; }
        [DataMember]
        public virtual ICollection<aspnet_PersonalizationPerUser> PersonalizationPerUser { get; set; }
        [DataMember]
        public virtual aspnet_Profile Profile { get; set; }
        [DataMember]
        public virtual ICollection<Log> Logs { get; set; }
        [DataMember]
        public virtual ICollection<Resource> ModifiedResources { get; set; }
        [DataMember]
        public virtual ICollection<aspnet_Roles> Roles { get; set; }
        [DataMember]
        public virtual ICollection<Request> ModifiedRequests { get; set; }
        [DataMember]
        public virtual ICollection<Request> Requests { get; set; }
        [DataMember]
        public virtual ICollection<Share> ModifiedShares { get; set; }
        [DataMember]
        public virtual ICollection<Share> Shares { get; set; }
    }
    
}
